### PR TITLE
[#11] Catch UnicodeEncodeErrors when printing output

### PR DESCRIPTION
**Pull request by alanking**

### CODE REVIEW

**Comment by d-w-moore** [comment]
Nice! The safety valve is to print the messy bytes object if there's  a utf-8 encode error. 
 If it prints the right stuff, I'd say ship it.

Only reservation might be (something @SwooshyCueb mentioned earlier) configuring streams to have a certain encoding.  Found this link: https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3 

Not sure if needed, though.  Might only apply if your container or OS has a non-standard locale setting ?

**Comment by d-w-moore** [comment]
Aha!!
Taking from the above link.
```
root@191b567ec9a1:/# python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys,codecs
>>> sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())
>>> sys.stdout.write(u'\u1000')
က>>> 
root@191b567ec9a1:/# python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.write(u'\u1000')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\u1000' in position 0: ordinal not in range(128)
>>> 
```
So, you do need to "recreate" the default streams to print unicode chars on (For example) ubuntu:18.04 ....

**Comment by d-w-moore** [comment]
And... basically ... `sys.stdout.write('xyz)  `followed by a `sys.stdout.flush( ) `is the same as:
```
print('xyz', file = sys.stdout, end = '')
```

**Comment by d-w-moore** [comment]
Oh, and the above session was done on a ubuntu:18.04 docker container.  They define locale as POSIX, apparently.

**Comment by trel** [comment]
nice find.

**Comment by alanking** [comment]
Oooh, interesting. I will try to give that a try soon, hopefully

**Comment by alanking** [comment]
The `codecs` solution seems to have worked for the `apt-get` install piece that I was struggling with, but then it failed on the next command which uses the same `subprocess_get_output` command:
```python
2022-04-06 14:52:17,479 ERROR - Traceback (most recent call last):
  File "/home/alanking/projects/irods_repos/irods_capability_indexing/irods_consortium_continuous_integration_test_hook.py", line 130, in <module>
    main()
  File "/home/alanking/projects/irods_repos/irods_capability_indexing/irods_consortium_continuous_integration_test_hook.py", line 100, in main
    irods_python_ci_utilities.subprocess_get_output(['sudo', '-EH', 'pip', 'install', 'unittest-xml-reporting==1.14.0'])
  File "/usr/local/lib/python3.6/dist-packages/irods_python_ci_utilities/irods_python_ci_utilities.py", line 45, in subprocess_get_output
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach())
  File "/usr/lib/python3.6/codecs.py", line 408, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.FileIO' object has no attribute 'detach'
```
This is blocking me from getting the plugins squared up for 4.3.0, so I'm wondering if it would be better to make an Enhancement for this and just use the try-except approach? I'm okay to keep trying to get this to go, just thought it might not be worth the time right now.

**Comment by trel** [comment]
yeah, either way - gotta get unblocked.   write it down and move on if that's where we are.

**Comment by alanking** [comment]
Oh, I guess putting the `sys.stdout` in the function is probably the cause of the issue. I didn't put together that Dan was actually replacing `sys.stdout` with the `StreamWriter` returned by `getwriter`.

**Comment by alanking** [comment]
I created #13 for the `codecs` solution. Sorry, gotta move this along.

Any other comments? If not, I will drop the latest commit (diff will go into the new issue for posterity), add #'s, and merge.

**Comment by trel** [comment]
i'm good.

**Comment by d-w-moore** [comment]
I think this is mentioned in the link I gave.  But you don't have to replace the stream either, just do this little bit 
```
alt_stdout = codecs.getwriter("utf-8")(sys.stdout)
```

**Comment by d-w-moore** [comment]
nevermind , that doesn't work either.

**Comment by alanking** [comment]
Okay. In that case, I will punt to the other issue. Onward!

**Pull request merged**
